### ISSUE TITLE
Add  Designated Folders 

### ISSUE THREAD

**Issue by Yogeshkarma** [vinayakn77/Hacktober_Fest_2024_Fork_Commit_Pull_Merge#86]
hey @vinayakn77 Assign this issue under hacktober fest 2024 label, where i will add the folders into the repo like array problems, game problems, linkedlist problems , greedy , Dynamic Programming and so on

**Comment by vinayakn77** [comment]
You can push you codes and i will merge here.

**Comment by Yogeshkarma** [comment]
assign the label as well buddy, i guess this is required @vinayakn77

**Comment by Yogeshkarma** [comment]
this issue is closed @vinayakn77
