### ISSUE TITLE
Banking Management System  designed to use an Oracle Database to handle banking activities

### ISSUE THREAD

**Issue by syedmaazsaeed** [vinayakn77/Hacktober_Fest_2024_Fork_Commit_Pull_Merge#89]
@vinayakn77 

I have developed a Python + Oracle-based banking system that I believe would be a great addition to your repository. It's easy to understand for beginners and also includes some advanced features. Everything works well, from the Oracle database connection to the CLI interface. I've also started working on a front-end using Tkinter.

If you give me permission, I can fork your repository, add the project, and submit a pull request. You can review it, and if it fits, merge it into the main branch.

Tell me  will this repository be included in Hacktoberfest 2024? Looking forward to your response.

**Comment by vinayakn77** [comment]
Done

**Comment by syedmaazsaeed** [comment]
Hi @vinayakn77,

I wanted to let you know that I have forked and starred your repository, and I have successfully uploaded my project as well. Please take some time to review it, and if it fits, kindly merge my pull request into the main branch.

This will ensure that my contribution is included in Hacktoberfest 2024 and will benefit both beginners and advanced users.

Looking forward to your response. Thanks

**Comment by vinayakn77** [comment]
Push the code in this repo i will merge it. Thank you

**Comment by syedmaazsaeed** [comment]
@vinayakn77 

Yes.I have pushed the code. You can review it, and if there's any issue, let me know. I can fix it right  now.Thanks.
